[package]
name = "my_macro"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.8"
syn = { version = "1.0.60", features = ["full", "extra-traits"] }
